drop index index_band_name;
drop index index_person_name;
drop index index_alias;
drop index index_composition_name;
drop index index_album_name;
drop index index_style_name;
drop index index_member_id;
drop index index_member_person_id;
drop index index_member_band_id;
